export type FlightType = "round" | "oneway";
export type CabinType = 
  | "M" // (economy)
  | "W" // (economy premium)
  | "C" // (business)
  | "F" // (first class)
export type FlyDaysType = "departure" | "arrival"
export type FlightLocale = 
  | "ae"
  | "ag"
  | "ar"
  | "at"
  | "au"
  | "be"
  | "bg"
  | "bh"
  | "br"
  | "by"
  | "ca"
  | "ca-fr"
  | "ch"
  | "cl"
  | "cn"
  | "co"
  | "ct"
  | "cz"
  | "da"
  | "de"
  | "dk"
  | "ec"
  | "ee"
  | "el"
  | "en"
  | "es"
  | "fi"
  | "fr"
  | "gb"
  | "gr"
  | "hk"
  | "hr"
  | "hu"
  | "id"
  | "ie"
  | "il"
  | "in"
  | "is"
  | "it"
  | "ja"
  | "jo"
  | "jp"
  | "ko"
  | "kr"
  | "kw"
  | "kz"
  | "lt"
  | "mx"
  | "my"
  | "nl"
  | "no"
  | "nz"
  | "om"
  | "pe"
  | "ph"
  | "pl"
  | "pt"
  | "qa"
  | "ro"
  | "rs"
  | "ru"
  | "sa"
  | "se"
  | "sg"
  | "sk"
  | "sr"
  | "sv"
  | "th"
  | "tr"
  | "tw"
  | "ua"
  | "uk"
  | "us"
  | "vn"
  | "za"
export type FlightCurrency = 
  | "AED"
  | "AFN"
  | "ALL"
  | "AMD"
  | "ANG"
  | "AOA"
  | "ARS"
  | "AUD"
  | "AWG"
  | "AZN"
  | "BAM"
  | "BBD"
  | "BDT"
  | "BGN"
  | "BHD"
  | "BIF"
  | "BMD"
  | "BND"
  | "BOB"
  | "BRL"
  | "BSD"
  | "BTC"
  | "BTN"
  | "BWP"
  | "BYR"
  | "BZD"
  | "CAD"
  | "CDF"
  | "CHF"
  | "CLF"
  | "CLP"
  | "CNY"
  | "COP"
  | "CRC"
  | "CUC"
  | "CUP"
  | "CVE"
  | "CZK"
  | "DJF"
  | "DKK"
  | "DOP"
  | "DZD"
  | "EEK"
  | "EGP"
  | "ERN"
  | "ETB"
  | "EUR"
  | "FJD"
  | "FKP"
  | "GBP"
  | "GEL"
  | "GGP"
  | "GHS"
  | "GIP"
  | "GMD"
  | "GNF"
  | "GTQ"
  | "GYD"
  | "HKD"
  | "HNL"
  | "HRK"
  | "HTG"
  | "HUF"
  | "IDR"
  | "ILS"
  | "IMP"
  | "INR"
  | "IQD"
  | "IRR"
  | "ISK"
  | "JEP"
  | "JMD"
  | "JOD"
  | "JPY"
  | "KES"
  | "KGS"
  | "KHR"
  | "KMF"
  | "KPW"
  | "KRW"
  | "KWD"
  | "KYD"
  | "KZT"
  | "LAK"
  | "LBP"
  | "LKR"
  | "LRD"
  | "LSL"
  | "LTL"
  | "LVL"
  | "LYD"
  | "MAD"
  | "MDL"
  | "MGA"
  | "MKD"
  | "MMK"
  | "MNT"
  | "MOP"
  | "MRO"
  | "MTL"
  | "MUR"
  | "MVR"
  | "MWK"
  | "MXN"
  | "MYR"
  | "MZN"
  | "NAD"
  | "NGN"
  | "NIO"
  | "NOK"
  | "NPR"
  | "NZD"
  | "OMR"
  | "PAB"
  | "PEN"
  | "PGK"
  | "PHP"
  | "PKR"
  | "PLN"
  | "PYG"
  | "QAR"
  | "QUN"
  | "RON"
  | "RSD"
  | "RUB"
  | "RWF"
  | "SAR"
  | "SBD"
  | "SCR"
  | "SDG"
  | "SEK"
  | "SGD"
  | "SHP"
  | "SLL"
  | "SOS"
  | "SRD"
  | "STD"
  | "SVC"
  | "SYP"
  | "SZL"
  | "THB"
  | "TJS"
  | "TMT"
  | "TND"
  | "TOP"
  | "TRY"
  | "TTD"
  | "TWD"
  | "TZS"
  | "UAH"
  | "UGX"
  | "USD"
  | "UYU"
  | "UZS"
  | "VEF"
  | "VND"
  | "VUV"
  | "WST"
  | "XAF"
  | "XAG"
  | "XAU"
  | "XCD"
  | "XDR"
  | "XOF"
  | "XPD"
  | "XPF"
  | "XPT"
  | "YER"
  | "ZAR"
  | "ZMK"
  | "ZMW"
  | "ZWL"

export interface IFlightQuery {
  fly_from: string;
  fly_to?: string;
  date_from: string;
  date_to: string;
  partner: string;
  v: number;
  to: string;
  nights_in_dst_from?: number;
  nights_in_dst_to?: number;
  return_from?: string;
  return_to?: string;
  max_fly_duration?: number;
  flight_type?: FlightType;
  adults?: number;
  children?: number;
  infants?: number;
  selected_cabins?: CabinType;
  mix_with_cabins?: CabinType;
  adult_hold_bag?: number;
  adult_hand_bag?: number;
  child_hold_bag?: number;
  child_hand_bag?: number;
  fly_days?: number[];
  fly_days_type?: FlyDaysType;
  ret_fly_days?: number[];
  ret_fly_days_type?: FlyDaysType;
  one_for_city?: boolean;
  only_working_days?: boolean;
  only_weekends?: boolean;
  one_per_date?: boolean;
  direct_flights?: boolean;
  locale?: FlightLocale;  
  partner_market?: string;  
  xml?: number;
  curr?: FlightCurrency;
  price_from?: number;
  price_to?: number;
  dtime_from?: string;
  dtime_to?: string;
  atime_from?: string;
  atime_to?: string;
  ret_dtime_from?: string;
  ret_dtime_to?: string;
  ret_atime_from?: string;
  ret_atime_to?: string;
  stopover_from?: string;
  stopover_to?: string;
  max_stopovers?: number;
  conn_on_diff_airport?: number;
  ret_from_diff_airport?: number;
  ret_to_diff_airport?: number;
  select_airlines?: string;
  select_stop_airport?: string;
  select_airlines_exclude?: boolean;
  select_stop_airport_exclude?: boolean;
  limit?: number;
  sort?: string;
  asc?: number;
}
